### ISSUE TITLE
No transparency in v3.2.1beta3

### ISSUE THREAD

**Issue by hguandl** [jasonwoodland/iTerm2-borderless#14]
Thank your for solving the strange line in Mojave in the release 
https://github.com/jasonwoodland/iTerm2-borderless/releases/tag/v3.2.1beta3. However I've found another problem. The transparency of the windows is not shown even if it is configured in the Preferences - Profile - Window. Would you please find out the problem?

In addition, the latest patch is still not updated to the repo. If you would like, we can also try to resolve the issue by reading your patch.

Thanks again for the patch!

**Comment by jasonwoodland** [comment]
Hey, it's because Mojave changed the way windows are drawn, as you can see in [PseudoTerminal.m L5438](https://github.com/gnachman/iTerm2/blob/master/sources/PseudoTerminal.m#L5438)

```objective-c
    // Sigh.
    // In Mojave, the window background is visible when the contentView is transparent.
    // This is generally a good thing because it means layers really work!
    // But there's a bug that the window title shows a broken vibrancy effect (issue 6964).
    // There's an opportunity for improvement here if there's a tab color and we know the
    // window isn't opaque we could set the titlebar's color, since that works again in 10.14.
    self.window.backgroundColor = [NSColor clearColor];
```

Because I mess with the titlebar, I patched this section to set the entire window background to a solid colour, and since I always have an opaque terminal, never thought twice about it haha.

If I keep the window transparent, only the terminal view has a semi-transparent/blurred background, not the titlebar area. It'd take some work figuring out how to move the terminal view up, and adding some extra padding.

Feel free to mess around yourself, if I find some time I may try to get it working.

I will be updating the patch, I'm just not sure it works < Mojave so I was waiting for it to be released.

**Comment by jasonwoodland** [comment]
@hguandl Well it took some work but here's what I got so far.
<img width="1537" alt="screen shot 2018-10-04 at 12 28 22 pm" src="https://user-images.githubusercontent.com/5356544/46449728-045b8880-c7d1-11e8-83ff-ccd6eac94ec8.png">

**Comment by veics** [comment]
is this fixed? because I do not have any transparency in the title bar :)
running macOS 10.15.4 with iTerm2 3.3.9
